### ISSUE TITLE
feature: refresh player data from lavalink and use a caching system

### ISSUE THREAD

**Issue by KagChi** [shipgirlproject/Shoukaku#182]

**Comment by 0t4u** [comment]
Do you want to refresh the player data from the lavalink instance or what do you want it to achieve?

**Comment by Deivu** [comment]
If im not mistaken, there is already functions for that.

```js
<Node>.rest.getPlayer(id) // (Lavalink player data)
<Shoukaku>.players.get(id) // (Shoukaku player data)
```

**Comment by KagChi** [comment]
i think that would be better with djs cache manager implementation ig, if you familiar with it tho

**Comment by 0t4u** [comment]
Why would that be beneficial?

**Comment by EvilG-MC** [comment]
I don't recommend using the djs cache

**Comment by KagChi** [comment]
> Why would that be beneficial? That would add some level of complexity.

naaah, i mean add fetch func to force fetch or get it from the cache just like djs cache manager

**Comment by KagChi** [comment]
> I don't recommend use the djs cache

who said use djs cache? i just said take the reference from djs cache manager, `fetch` one

**Comment by 0t4u** [comment]
Correct me if I am wrong, but since Shoukaku does not "garbage collect" (remove instances of) players, and also already has the `Node#rest.getPlayer()` function to get raw data from Lavalink, there isn't really a point in fetching the data again since it would just be identical to the cached data anyways. Since a Player is created when you join a voice channel and gets destroyed after disconnecting from the voice channel, all active Players are being actively handled by Shoukaku anyways, unless something goes really wrong and Shoukaku is completely out of sync from Lavalink.

**Comment by 0t4u** [comment]
@KagChi @EvilG-MC

**Comment by EvilG-MC** [comment]
> @KagChi @EvilG-MC

I really agree with your point, because after giving it a lot of thought, a `fetch` is really a bit unnecessary.
I think its only purpose (which I really don't think is the case) is in case the data for some specific reason is out of date.

**Comment by EvilG-MC** [comment]
For my part I could say that I'm fine with what is currently available.

**Comment by 0t4u** [comment]
I'm going to see if I can get into contact/get Saya to get into contact with some bot developers who use Shoukaku in production at scale to see if they have a use case for this, if they don't then @KagChi is welcome to implement it and open a PR
